AXF_Project/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('app/',include('mainapp.urls'))
]

mainapp/urls.py
from django.urls import path

from mainapp import views

urlpatterns = [
    path("",views.home),
    path('market/<int:categoryid>/<int:childcid>/<int:sortid>',views.market),
    path('cart',views.cart),
    path('mine',views.mine),
    path('register',views.register),
    path('login',views.login),
    path('upload',views.upload),
    path('delectToken',views.delectToken),
    path('userNumber',views.userNumber),
    path('cart',views.cart),
    path('select/<int:cart_id>',views.selectCart),
    path('selectCnt/<int:id>',views.selectCnt),
    path('addselectCnt/<int:id>',views.addselectCnt),
    path('addgoodtoCart/<int:goodID>',views.addgoodtoCart),
    path('order/<str:num>',views.order),
    path('pay/<str:num>/<int:payType>',views.pay),
    path('selectOrder',views.selectOrder),
    path('waitpay',views.waitpay),
    path('waitgood',views.waitgood),
    path('suregood/<str:num>',views.suregood),
    path('useraddress',views.useraddress),
    path('deleteadre/<int:id>',views.deleteadre),
    path('defaultade/<int:id>',views.defaultade)
]

mainapp/models.py
from django.db import models


# Create your models here.

class TopModel(models.Model):
    trackid = models.CharField(primary_key=True, max_length=10)
    img = models.CharField(max_length=300)
    name = models.CharField(max_length=50)

    class Meta:
        abstract = True


class TopWheel(TopModel):
    class Meta:
        db_table = "axf_wheel"  # 指定表名


class TopMenu(TopModel):
    position = models.IntegerField(default=1)

    class Meta:
        db_table = "axf_nav"  # 导航菜单表


class Topmustbuy(TopModel):
    class Meta:
        db_table = "axf_mustbuy"  # 必买菜单表


class TopShop(TopModel):
    position = models.IntegerField(default=1)

    class Meta:
        db_table = "axf_shop"  # 热销帮及商品分类


class TopMainShow(TopModel):
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)

    # img1 = models.CharField(max_length=300)
    # childcid1 = models.CharField(max_length=20)
    # productid1 = models.CharField(max_length=30)
    # longname1 = models.CharField(max_length=50)
    # price1 = models.CharField(max_length=10)
    # marketprice1 = models.CharField(max_length=10)
    #
    #
    # img2 = models.CharField(max_length=300)
    # childcid2 = models.CharField(max_length=20)
    # productid2 = models.CharField(max_length=30)
    # longname2 = models.CharField(max_length=50)
    # price2 = models.CharField(max_length=10)
    # marketprice2 = models.CharField(max_length=10)
    #
    # img3 = models.CharField(max_length=300)
    # childcid3 = models.CharField(max_length=20)
    # productid3 = models.CharField(max_length=30)
    # longname3 = models.CharField(max_length=50)
    # price3 = models.CharField(max_length=10)
    # marketprice3 = models.CharField(max_length=10)

    class Meta:
        db_table = "axf_mainshow"


class MainChild(models.Model):
    img = models.CharField(max_length=300)
    childcid = models.CharField(max_length=20)
    productid = models.CharField(max_length=30)
    longname = models.CharField(max_length=50)
    price = models.CharField(max_length=10)
    marketprice = models.CharField(max_length=10)

    class Meta:
        abstract = True


class TopMainChild(MainChild):
    topMainShow = models.ForeignKey(TopMainShow, on_delete=models.CASCADE)

    class Meta:
        db_table = "axf_mainchild"


# 食品分类模型
class FoodTypes(models.Model):
    typeid = models.CharField(max_length=10)
    typename = models.CharField(max_length=20)
    typesort = models.IntegerField(default=1)
    childtypenames = models.CharField(max_length=150)

    class Meta:
        db_table = "axf_foodtypes"


#商品模型类
class Goods(models.Model):
    #商品id
    productid = models.CharField(max_length=10, primary_key=True)
    #商品图片
    productimg = models.CharField(max_length=300)
    #商品名称
    productname = models.CharField(max_length=100)
    #商品长名称
    productlongname = models.CharField(max_length=100)
    #是否精选
    isxf = models.BooleanField(default=1)
    #是否买一送一
    pmdesc = models.IntegerField(default=1)
    #规格
    specifics = models.CharField(max_length=100)
    #价格
    price = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    #超市价格
    marketprice = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    #组id
    categoryid = models.IntegerField(default=0)
    #子类组id
    childcid = models.IntegerField(default=0)
    #子类组名称
    childcidname = models.CharField(max_length=100)
    #详情页id
    dealerid = models.CharField(max_length=20)
    #库存
    storenums = models.IntegerField(default=1)
    #销量
    productnum = models.BigIntegerField(default=0)

    class Meta:
        db_table = 'axf_goods'


class UserManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(state=True)


class User(models.Model):
    usernumber = models.CharField(max_length=20)
    username = models.CharField(max_length=20)
    userpasswd = models.CharField(max_length=100)
    userphone = models.CharField(max_length=11)
    useraaddress = models.CharField(max_length=100)
    userphoto = models.ImageField(upload_to='userphoto', null=True)
    token = models.CharField(max_length=200, null=True, default='')
    money = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    state = models.BooleanField(default=True, verbose_name='用户状态')

    objects = UserManager()

    class Meta:
        db_table = 'axf_user'

    def toDict(self):
        return {'usernumber': self.usernumber,
                'username': self.username,
                'userpasswd': self.userpasswd,
                'userphone': self.userphone,
                'userphoto': self.userphoto.name,
                'useraaddress': self.useraaddress,
                'token': self.token}

    def delete(self, using=None, keep_parents=False):
        self.state = False
        self.save()
        return 'success'


# 收件地址模型
class DeliveryAddress(models.Model):
    name = models.CharField(max_length=20, verbose_name='收件人')
    phone = models.CharField(max_length=12, verbose_name='收件人手机号码')
    address_detail = models.TextField(default='', verbose_name='收货地址')

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    only=models.IntegerField(default=0)
    class Meta:
        db_table = 'axf_address'


# 购物车模型
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    cnt = models.IntegerField(default=1)

    # 是否被选中
    isSelected = models.BooleanField(default=True)

    class Meta:
        db_table = 'axf_cart'

#订单模型
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # 订单的收货地址
    orderAddress = models.ForeignKey(DeliveryAddress, on_delete=models.SET_NULL, null=True)
    # 订单的单号
    orderNum = models.CharField(primary_key=True, max_length=50, verbose_name='订单号')

    # 订单的总金额
    orderPrice = models.DecimalField(max_digits=10, decimal_places=2,default=0)

    #支付方式
    pay_types=((0,'余额'),(1,'支付宝'),(2,'微信'))
    payType=models.IntegerField(choices=pay_types,default=0)

    @property
    def payTypeName(self):
        return self.pay_types[self.payType][1]

    # 订单的支付状态
    pay_states = ((0, '待支付'), (1, '已支付'), (2, '正在支付中'), (3, '已退款'))
    payState = models.IntegerField(choices=pay_states,default=0)

    @property
    def payStatesName(self):
        return self.pay_states[self.payState][1]

    # 订单的派送状态
    order_states = ((0, '待派送'), (1, '已派送'), (2, '已送达'), (3, '已签售'), (4, '拒收'), (5, '未到达'))
    orderState = models.IntegerField(choices=order_states,default=0)

    @property
    def orderStateName(self):
        return self.order_states[self.orderState][1]

    # 生成订单时间
    orderTime = models.DateTimeField(auto_now_add=True)

    # 订单修改时间
    orderLastTime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'axf_order'


#订单明细
class OrderGoogs(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    goods =models.ForeignKey(Goods,on_delete=models.SET_NULL,null=True)
    cnt = models.IntegerField(default=1)
    price = models.DecimalField(default=0,max_digits=10,decimal_places=2,verbose_name='小计')

    class Meta:
        db_table='axf_order_goods'

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load static from staticfiles %} {# 旧版本需要加from staticfiles，可省略 #}
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">

    {% block extCss %}
        {# 扩展的css样式文件 #}
    {% endblock %}

</head>
<body>
<header></header>
{% block content %}
    {#  内容区域  #}
{% endblock %}

<footer>
    <a class="home" href="/">
        <dl>
            <dt><span></span></dt>
            <dd>主页</dd>
        </dl>
    </a>
    <a class="market" href="/app/market/0/0/0">
        <dl>
            <dt><span></span></dt>
            <dd>闪购</dd>
        </dl>
    </a>
    <a class="cart" href="/app/cart">
        <dl>
            <dt><span></span></dt>
            <dd>购物车</dd>
        </dl>
        <p id="cartCnt">0</p>
    </a>
    <a class="my" href="/app/mine">
        <dl>
            <dt><span></span></dt>
            <dd>我的</dd>
        </dl>
    </a>
</footer>
<script src="{% static 'main/js/jquery.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/swiper.min.js' %}"></script>
<script src="{% static 'main/js/base.js' %}"></script>
{% block extJs %}
    {#  扩展的JS  #}
{% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block content %}

    <div id="cart">
        <h3>我的购物车</h3>
        <section class="full">

            <section>
                {#  收货信息 #}
                <ul>
                    <li style="border-bottom: 1px solid gray;">
                        <span style="font-size: 0.35rem;color: dodgerblue">收件地址信息</span><a href="#"></a>
                        <a href="/app/useraddress">
                        <span style="font-size: 0.35rem;color: dodgerblue;
                            margin-left: 5rem;cursor: pointer;">选择收件地址</span></a>

                    </li>
                    <li>
                        <div class="clear">
                            <p class="infoJustify"><strong>收件人: </strong></p>
                            <p><span>{{ myAddress.name }}</span></p>
                        </div>
                        <div class="clear">
                            <p class="infoJustify"><strong>手机号: </strong></p>
                            <p><span>{{ myAddress.phone }}</span></p>
                        </div>
                        <div class="clear">
                            <p class="infoJustify"><strong>收件地址: </strong></p>
                            <p><span>{{ myAddress.address_detail }}</span></p>
                        </div>
                    </li>
                </ul>

                <section class="bill">
                    <p>闪送超市</p>
                    <p>¥0起送,22:00前满¥30免运费</p>
                    <a>凑单专区</a>
                </section>


                <section class="delivery">
                    <span>收货时间</span>
                    <span>一小时送达</span>
                    <a>可预订&gt;</a>
                </section>

                <section class="delivery">
                    <span>收货备注</span>
                    <input type="text"
                           name="noteText"
                           placeholder="可输入20字以内特殊要求内容"/>
                </section>

                {#   购物车中物品  #}
                <menu>
                    <ul>
                        {% for card in cards %}

                            <li class="menuList">
                                <div class="confirm">
                                <span class="isChose">
                                    <span id="{{ card.id }}">
                                        {% if card.isSelected %}
                                            √
                                        {% endif %}
                                    </span>
                                </span>
                                </div>
                                <a href="#">
                                    <img src="{{ card.goods.productimg }}"/>
                                    <p>&nbsp;{{ card.goods.productname }}</p>
                                    <span>&nbsp;¥{{ card.goods.marketprice }}</span>
                                </a>
                                <section>
                                    <button class="subShopping"><span>-</span></button>
                                    <span title="{{ card.id }}">{{ card.cnt }}</span>
                                    <button class="addShopping"><span>+</span></button>
                                </section>

                            </li>
                        {% endfor %}
                        <li class="payTheBill">
                            <div class="confirm">
                            <span id="allChose">
                                <span></span>
                            </span>
                            </div>
                            <p><span>全选</span><span>共计:</span><span id="totalPrice">{{ totalprice }}</span></p>

                        </li>
                        <li style="background-color:white;text-align: right;">
                            {#                            <a id="selectOrder" class="btn btn-primary " style="float: left;margin-top:32px;">所有订单</a>#}
                            <a id="toOrder" class="btn btn-info" style="margin: 0.5rem;">立即支付</a>
                        </li>
                    </ul>
                </menu>
            </section>

        </section>

    </div>

{% endblock %}

{% block extJs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}
{% block extJs %}
    <script type="text/javascript" src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="login">
        <div>
            <a href="/app/"  class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span>返回主页</a>
            <a href="register" style="float: right" class="btn btn-default">注册<span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>

        <hr style="height:1px;border:none;border-top:1px solid #555555;"/>
        <div id="box">
            <form action="login" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-addon">账号</span>
                    <input  name="number" type="text" title="账号不能为空" class="form-control"
                           placeholder="账号长度为6到11位" aria-describedby="basic-addon1">
                </div>
                <p class="error">账号不能为空</p>
                <div class="input-group" style="margin-top: 10px">
                    <span class="input-group-addon">密码</span>
                    <input  name="passwd" type="password" title="密码不能为空" class="form-control"
                           placeholder="密码长度为6到16位" aria-describedby="basic-addon1">
                </div>
                <p class="error">密码不能为空</p>
                <div class="input-group" style="margin: auto;margin-top: 0.8rem">
                    <button type="button" class="btn btn-primary" onclick="submitForm()">登录</button>
                    {#                    <button class="btn-link" style="margin-left: 10px">已有用户登录</button>#}
                </div>
            </form>
            {% if error %}
                <h2>{{ error }}</h2>
            {% endif %}
{#        {% if error %}#}
{#            <script>#}
{#                    $(function () {#}
{#                        if(confirm('{{ error }}')){#}
                            {#window.opener.doucument.location.reload();#}
{#                        }#}
{##}
{#                    })#}
{#            </script>#}
{#        {% endif %}#}


        </div>
    </div>



{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'order/css/order.css' %}">
{% endblock %}
{% block content %}
    <div id="order">
        <p>
            <button id='backBtn' class="btn btn-xs btn-info">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </button>
        <div class="clearfix"></div>
        <h3><strong>我的订单</strong></h3>
        </p>

        <div>
            <section class="orderInfo">
                <p><strong>订单金额:</strong><span style="color: red;margin-left: 10px">&nbsp;¥{{ order.orderPrice }}</span>
                </p>
                <p><strong>收货信息:</strong><br/>
                    <span style="margin-left: 10px">
                        <span style="color: #6c69ff;font-weight: bold">address:</span>{{ order.orderAddress.address_detail }}</span><br/>
                    <span style="margin-left: 10px"><span
                            style="color: #6c69ff;font-weight: bold">username:</span>{{ order.user.username }}</span><br/>
                    <span style="margin-left: 10px"><span
                            style="color: #6c69ff;font-weight: bold">tel:</span>{{ order.user.userphone }}</span>
                </p>
            </section>

            <menu id="orderGoods">
                <ul>
                    {% for orderitem in order.ordergoogs_set.all %}

                        <li>
                            <dl>
                                <dt>
                                    <img src="{{ orderitem.goods.productimg }}">
                                </dt>
                                <dd>
                                    {{ orderitem.goods.productname|truncatechars:8 }} {# truncatechars截断字符 #}
                                </dd>
                            </dl>
                        </li>
                    {% endfor %}
                </ul>
            </menu>

            <section id="payBtnDiv" title="{{ order.orderNum }}">
                <button title="0" class="btn btn-primary">余额支付</button>
                <button title="1" class="btn btn-info">支付宝</button>
                <button title="2" class="btn btn-success">微信支付</button>
            </section>
        </div>

        <div class="modal fade in" tabindex="1" role="dialog" id="myModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">提示</h4>
                    </div>
                    <div id="payMsg" class="modal-body">
                        <p>&hellip;</p>
                    </div>
{#                    <div class="modal-footer">#}
{#                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
{#                        <button type="button" class="btn btn-primary">Save changes</button>#}
{#                    </div>#}
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
    </div>

{% endblock %}




{% block extJs %}
    <script src="{% static 'order/js/order.js' %}"></script>
{% endblock %}

templates/selectOrder.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'selectOrder/css/selectOrder.css' %}">
{% endblock %}

{% block content %}
    <div id="selectOrder">
        <p>
            <button id='backBtn' class="btn btn-xs btn-info">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </button>
        <div class="clearfix"></div>
        {% if data == 1 %}
            <h3><strong>全部订单</strong></h3>
        {% elif data == 2 %}
            <h3><strong>待付款订单</strong></h3>
        {% endif %}

        </p>
        <menu class="full">
            <ul>
                {% for order in orders %}
                    <li class="menuList">
                        {#                        <div class="confirm">#}
                        {#                                <span class="isChose">#}
                        {#                                    <span id="{{ card.id }}">#}
                        {#                                        {% if card.isSelected %}#}
                        {#                                            √#}
                        {#                                        {% endif %}#}
                        {#                                    </span>#}
                        {#                                </span>#}
                        {#                        </div>#}
                        <a href="#">
                            {# 获取订单第一个商品图片 #}
                            <img src="{{ order.ordergoogs_set.all.last.goods.productimg }}"/>
                            <span>订单编号：&nbsp;{{ order.orderNum }}</span><br/>
                            <span>订单金额：&nbsp;¥{{ order.orderPrice }}</span><br/>
                            <span>下单时间：&nbsp;{{ order.orderTime }}</span>
                        </a>
                        <section>
                            {% if order.payState == 0 %}
                                <a title="{{ order.orderNum }}" class="btn btn-info toOrder"
                                   style="margin-right: 0.5rem;">立即支付</a>
                            {% else %}
                                <a class="btn btn-primary" style="margin-right: 0.5rem;">已完成交易</a>
                            {% endif %}
                        </section>

                    </li>
                {% endfor %}
            </ul>
        </menu>

    </div>

{% endblock %}




{% block extJs %}
    <script src="{% static 'selectOrder/js/selectOrder.js' %}"></script>
{% endblock %}

templates/useraddress.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'useraddress/css/useraddress.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/layer.css' %}">
{% endblock %}

{% block content %}
    <div id="selectOrder">
        <p>
            <button id='backBtn' class="btn btn-xs btn-info">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </button>
        <div class="clearfix"></div>
        {#        {% if data == 1 %}#}
        {#            <h3><strong>全部订单</strong></h3>#}
        {#        {% elif data == 2 %}#}
        {#            <h3><strong>待付款订单</strong></h3>#}
        {#        {% endif %}#}
        <h3><strong>收货地址管理</strong></h3>
        </p>
        </p>
        <menu class="full">
            <ul>
                {% for address in deliveryAddress %}
                    <li class="menuList">
                        <div class="confirm">
                            <span id="allChose">
                                <span>
                                {% if address.only == 1 %}
                                    √
                                {% endif %}
                                </span>
                            </span>
                        </div>
                        <a href="#" style="margin-top: 20px;margin-left: 10px;">
                            {#                            <img src="{{ order.ordergoogs_set.all.last.goods.productimg }}"/>#}
                            <span>收货人：&nbsp;{{ address.name }}</span><br/>
                            <span>联系电话：&nbsp;{{ address.phone }}</span><br/>
                            <span>收货地址：&nbsp;{{ address.address_detail }}</span>
                        </a>
                        <section style="margin-top: 1rem">
                            <a title="{{ address.id }}" class="btn btn-info toOrder"
                               style="margin-right: 0.5rem;">编辑</a>
                            <a title="{{ address.id }}" class="btn btn-primary adreDelete"
                               style="margin-right: 0.5rem;">删除</a>
                            <a title="{{ address.id }}" class="btn btn-success defaultad"
                               style="">设为默认</a>
                        </section>

                    </li>
                {% endfor %}
            </ul>
        </menu>

    </div>


    {# 模态框 #}
    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">提示</h4>
                </div>
                <div id="payMsg" class="modal-body">
                    <p>&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="sure" type="button" class="btn btn-primary">确定</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}




{% block extJs %}
    <script src="{% static 'useraddress/js/useraddress.js' %}"></script>
    <script src="{% static 'main/js/layer.js' %}"></script>
{% endblock %}

templates/waitgood.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'selectOrder/css/selectOrder.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/layer.css' %}">
{% endblock %}

{% block content %}
    <div id="selectOrder">
        <p>
            <button id='backBtn' class="btn btn-xs btn-info">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </button>
        <div class="clearfix"></div>
        {#        {% if data == 1 %}#}
        {#            <h3><strong>全部订单</strong></h3>#}
        {#        {% elif data == 2 %}#}
        {#            <h3><strong>待付款订单</strong></h3>#}
        {#        {% endif %}#}
        <h3><strong>待收货订单</strong></h3>
        </p>
        <menu class="full">
            <ul>
                {% for order in orders %}
                    <li class="menuList">
                        {#                        <div class="confirm">#}
                        {#                                <span class="isChose">#}
                        {#                                    <span id="{{ card.id }}">#}
                        {#                                        {% if card.isSelected %}#}
                        {#                                            √#}
                        {#                                        {% endif %}#}
                        {#                                    </span>#}
                        {#                                </span>#}
                        {#                        </div>#}
                        <a href="#">
                            {# 获取订单第一个商品图片 #}
                            <img src="{{ order.ordergoogs_set.all.last.goods.productimg }}"/>
                            <span>订单编号：&nbsp;{{ order.orderNum }}</span><br/>
                            <span>订单金额：&nbsp;¥{{ order.orderPrice }}</span><br/>
                            <span>下单时间：&nbsp;{{ order.orderTime }}</span>
                        </a>
                        <section>
                            {% if order.orderState == 0 %}
                                <span style="text-align: center;color: orange">订单状态：待派送</span><br/>
                                <a title="{{ order.orderNum }}" class="btn btn-warning toOrder"
                                   style="margin-right: 0.5rem;">确认收货</a>
                            {% elif order.orderState == 1 %}
                                <span style="text-align: center">订单状态：已发货</span><br/>
                                <a title="{{ order.orderNum }}" class="btn btn-info toOrder"
                                   style="margin-right: 0.5rem;">确认收货</a>
                            {% elif order.orderState == 2 %}
                                <span style="text-align: center;color: green">订单状态：已送达</span><br/>
                                <a title="{{ order.orderNum }}" class="btn btn-success toOrder"
                                   style="margin-right: 0.5rem;">确认收货</a>
                            {% elif order.orderState == 4 %}
                                <span style="text-align: center;color: red">订单状态：已拒收</span><br/>
                                <a title="{{ order.orderNum }}" class="btn btn-danger aftersale"
                                   style="margin-right: 0.5rem;">退货/售后</a>
                            {% elif order.orderState == 5 %}
                                <span style="text-align: center;color: red">订单状态：未到达</span><br/>
                                <a title="{{ order.orderNum }}" class="btn btn-danger aftersale"
                                   style="margin-right: 0.5rem;">退货/售后</a>
                            {% endif %}
                        </section>

                    </li>
                {% endfor %}
            </ul>
        </menu>

    </div>


    {# 模态框 #}
    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button  type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">提示</h4>
                </div>
                <div id="payMsg" class="modal-body">
                    <p>&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="sure" type="button" class="btn btn-primary">确定</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}




{% block extJs %}
    <script src="{% static 'waitgood/js/waitgood.js' %}"></script>
    <script src="{% static 'main/js/layer.js' %}"></script>
{% endblock %}